const flagData = [
    {
        id: 1,
        title: "Princess treatment",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["omtanke", "romantikk", "innsats"],
        description: "Personen viser ekstra omtanke, innsats og romantisk interesse uten å presse deg eller forvente noe tilbake.",
        advice: "Dette kan være et green flag når det føles trygt, ekte og stabilt over tid. Vanlig respekt er bare minimum, mens princess treatment er noe ekstra."
    },
    {
        id: 2,
        title: "Love bombing",
        category: "red",
        score: 5,
        severity: "Veldig alvorlig",
        severityLevel: 5,
        isBareMinimum: false,
        themes: ["intensitet", "press", "manipulasjon"],
        description: "Personen gir veldig mye oppmerksomhet, komplimenter, gaver eller sterke følelser veldig tidlig, slik at det kan føles intenst eller pressende.",
        advice: "Dette kan være et red flag hvis det går for fort, føles manipulerende, eller hvis personen bruker det for å få rask nærhet eller kontroll."
    },
    {
        id: 3,
        title: "Respekterer grensene dine",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: true,
        themes: ["grenser", "respekt", "trygghet"],
        description: "Personen lytter når du sier nei, trenger tid, eller ikke vil gjøre noe.",
        advice: "Dette er et viktig green flag, men også noe som burde være grunnleggende i alle relasjoner."
    },
    {
        id: 4,
        title: "Kommuniserer tydelig",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["kommunikasjon", "ærlighet", "trygghet"],
        description: "Personen sier hva de mener, er ærlig om intensjoner og gir ikke unødvendige mixed signals.",
        advice: "Tydelig kommunikasjon gjør det lettere å forstå hvor man står."
    },
    {
        id: 5,
        title: "Holder avtaler",
        category: "minimum",
        score: 0,
        severity: "Bare minimum",
        severityLevel: 0,
        isBareMinimum: true,
        themes: ["respekt", "tid", "ansvar"],
        description: "Personen møter opp, gir beskjed ved endringer og respekterer tiden din.",
        advice: "Dette er bra, men det er også noe man egentlig bør kunne forvente."
    },
    {
        id: 6,
        title: "Sier unnskyld når de gjør feil",
        category: "minimum",
        score: 0,
        severity: "Bare minimum",
        severityLevel: 0,
        isBareMinimum: true,
        themes: ["ansvar", "modenhet", "kommunikasjon"],
        description: "Personen klarer å ta ansvar uten å legge all skyld over på deg.",
        advice: "Å kunne si unnskyld er grunnleggende moden oppførsel."
    },
    {
        id: 7,
        title: "Behandler deg med respekt",
        category: "minimum",
        score: 0,
        severity: "Bare minimum",
        severityLevel: 0,
        isBareMinimum: true,
        themes: ["respekt", "trygghet"],
        description: "Personen snakker ordentlig til deg og behandler deg som et menneske med egne følelser og grenser.",
        advice: "Dette er ikke noe ekstraordinært. Det er minimum i en sunn relasjon."
    },
    {
        id: 8,
        title: "Husker små ting du har sagt",
        category: "green",
        score: -1,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["omtanke", "oppmerksomhet", "interesse"],
        description: "Personen legger merke til detaljer og viser at de faktisk lytter.",
        advice: "Dette kan være et fint green flag når det skjer naturlig og ikke brukes for å imponere for mye."
    },
    {
        id: 9,
        title: "Gjør innsats for å planlegge ting",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["innsats", "prioritering", "dating"],
        description: "Personen tar initiativ til å planlegge dates, avtaler eller tid sammen.",
        advice: "Dette kan være et green flag fordi det viser at personen ikke bare forventer at du skal gjøre alt."
    },
    {
        id: 10,
        title: "Gir mixed signals",
        category: "yellow",
        score: 2,
        severity: "Litt problematisk",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["usikkerhet", "kommunikasjon", "mixed signals"],
        description: "Personen virker interessert én dag, men kald eller fjern neste dag.",
        advice: "Dette trenger ikke alltid være alvorlig, men hvis det skjer ofte, kan det skape usikkerhet."
    },
    {
        id: 11,
        title: "Svarer bare når det passer dem",
        category: "yellow",
        score: 2,
        severity: "Bør følges med på",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["kommunikasjon", "prioritering", "ubalansere"],
        description: "Personen forventer kanskje oppmerksomhet fra deg, men gir lite tilbake selv.",
        advice: "Se om dette er et mønster, eller om det bare skjer av og til."
    },
    {
        id: 12,
        title: "Unngår å snakke om hva dere er",
        category: "yellow",
        score: 2,
        severity: "Bør følges med på",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["situationship", "uklarhet", "kommunikasjon"],
        description: "Personen unngår samtaler om intensjoner, grenser eller hvor relasjonen er på vei.",
        advice: "I casual dating kan noe uklarhet være vanlig, men hvis du trenger tydelighet, er det lov å spørre."
    },
    {
        id: 13,
        title: "Blir defensiv av små spørsmål",
        category: "yellow",
        score: 2,
        severity: "Litt problematisk",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["kommunikasjon", "konflikt", "modenhet"],
        description: "Personen reagerer sterkt eller irritert selv når du spør rolig om noe.",
        advice: "Dette kan gjøre det vanskelig å ta opp ting. Se om personen klarer å roe seg og snakke ordentlig etterpå."
    },
    {
        id: 14,
        title: "Skjuler deg for venner eller familie",
        category: "yellow",
        score: 3,
        severity: "Bør følges med på",
        severityLevel: 3,
        isBareMinimum: false,
        themes: ["hemmelighold", "prioritering", "usikkerhet"],
        description: "Personen holder deg skjult eller unngår å vise at dere har kontakt.",
        advice: "Dette kan bety ulike ting avhengig av situasjon, men det kan være verdt å spørre tydelig om."
    },
    {
        id: 15,
        title: "Flørter mye med andre foran deg",
        category: "yellow",
        score: 3,
        severity: "Bør følges med på",
        severityLevel: 3,
        isBareMinimum: false,
        themes: ["respekt", "usikkerhet", "grenser"],
        description: "Personen oppfører seg flørtete med andre på en måte som gjør deg usikker eller ukomfortabel.",
        advice: "Dette bør vurderes ut fra hva dere har avtalt, men følelsen din er fortsatt verdt å ta på alvor."
    },
    {
        id: 16,
        title: "Blir sur når du ikke svarer raskt",
        category: "red",
        score: 4,
        severity: "Alvorlig",
        severityLevel: 4,
        isBareMinimum: false,
        themes: ["kontroll", "forventninger", "kommunikasjon"],
        description: "Personen reagerer negativt hvis du ikke svarer med en gang, selv om du har ditt eget liv.",
        advice: "Dette kan handle om kontroll eller urealistiske forventninger, spesielt hvis det skjer ofte."
    },
    {
        id: 17,
        title: "Kontrollerer hvem du snakker med",
        category: "red",
        score: 5,
        severity: "Veldig alvorlig",
        severityLevel: 5,
        isBareMinimum: false,
        themes: ["kontroll", "sjalusi", "grenser"],
        description: "Personen prøver å bestemme hvem du kan snakke med, møte eller følge på sosiale medier.",
        advice: "Dette er et tydelig red flag fordi det handler om kontroll, ikke omsorg."
    },
    {
        id: 18,
        title: "Presser deg til noe du ikke vil",
        category: "red",
        score: 5,
        severity: "Veldig alvorlig",
        severityLevel: 5,
        isBareMinimum: false,
        themes: ["press", "grenser", "trygghet"],
        description: "Personen prøver å få deg til å gjøre noe selv om du har sagt nei eller virker ukomfortabel.",
        advice: "Dette er et alvorlig red flag. Grenser skal respekteres."
    },
    {
        id: 19,
        title: "Skylder alltid på deg",
        category: "red",
        score: 4,
        severity: "Alvorlig",
        severityLevel: 4,
        isBareMinimum: false,
        themes: ["ansvar", "manipulasjon", "konflikt"],
        description: "Personen tar aldri ansvar og får deg til å føle at alt er din feil.",
        advice: "Dette kan bli veldig slitsomt over tid. Legg merke til om personen klarer å ta ansvar for egen oppførsel."
    },
    {
        id: 20,
        title: "Gjør deg redd for reaksjonen deres",
        category: "red",
        score: 5,
        severity: "Veldig alvorlig",
        severityLevel: 5,
        isBareMinimum: false,
        themes: ["trygghet", "kontroll", "frykt"],
        description: "Du føler at du må passe på hva du sier eller gjør fordi personen kan reagere sterkt.",
        advice: "Dette er alvorlig. Hvis du føler deg utrygg, snakk med noen du stoler på."
    },
    {
        id: 21,
        title: "Ghoster og kommer tilbake igjen",
        category: "yellow",
        score: 3,
        severity: "Bør følges med på",
        severityLevel: 3,
        isBareMinimum: false,
        themes: ["ghosting", "ustabilitet", "kommunikasjon"],
        description: "Personen forsvinner uten forklaring og kommer tilbake når det passer dem.",
        advice: "Dette kan skape en utrygg dynamikk, spesielt hvis det skjer flere ganger."
    },
    {
        id: 22,
        title: "Bruker sjalusi som bevis på kjærlighet",
        category: "red",
        score: 4,
        severity: "Alvorlig",
        severityLevel: 4,
        isBareMinimum: false,
        themes: ["sjalusi", "kontroll", "romantisering"],
        description: "Personen fremstiller sjalusi eller kontroll som om det betyr at de bryr seg.",
        advice: "Omsorg skal ikke føles som overvåkning eller kontroll."
    },
    {
        id: 23,
        title: "Snakker stygt om alle ekser",
        category: "ick",
        score: 1,
        severity: "Mildt varsel",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["ekser", "ansvar", "modenhet"],
        description: "Personen beskriver alle tidligere partnere som gale, dårlige eller problemet.",
        advice: "Dette kan være en ick, men også et tegn på at personen ikke tar ansvar for egen rolle."
    },
    {
        id: 24,
        title: "Er frekk mot ansatte",
        category: "ick",
        score: 2,
        severity: "Negativt tegn",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["respekt", "holdning", "oppførsel"],
        description: "Personen behandler servitører, butikkansatte eller andre servicearbeidere dårlig.",
        advice: "Hvordan noen behandler folk de ikke må imponere, kan si mye om holdninger."
    },
    {
        id: 25,
        title: "Skryter ekstremt mye",
        category: "ick",
        score: 1,
        severity: "Mildt varsel",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["ego", "selvbilde", "dating"],
        description: "Personen gjør samtalen veldig mye om seg selv og hvor imponerende de er.",
        advice: "Dette er ikke nødvendigvis alvorlig alene, men det kan bli slitsomt hvis personen ikke viser interesse for deg."
    },
    {
        id: 26,
        title: "Gjør alt til en konkurranse",
        category: "ick",
        score: 1,
        severity: "Mildt varsel",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["ego", "kommunikasjon", "modenhet"],
        description: "Personen må hele tiden vinne, ha rett eller være bedre enn andre.",
        advice: "Dette kan være en ick, spesielt hvis det gjør at samtaler føles tunge eller lite trygge."
    },
    {
        id: 27,
        title: "Viser interesse uten å presse",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["interesse", "respekt", "trygghet"],
        description: "Personen viser at de liker deg, men lar deg ha tid, grenser og eget tempo.",
        advice: "Dette er et sunt tegn fordi interesse ikke skal føles som press."
    },
    {
        id: 28,
        title: "Gir komplimenter som føles ekte",
        category: "green",
        score: -1,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["komplimenter", "trygghet", "omtanke"],
        description: "Personen gir komplimenter som føles naturlige og respektfulle, ikke overdrevne eller pressende.",
        advice: "Dette kan være et green flag når det føles rolig og ekte."
    },
    {
        id: 29,
        title: "Forventer ros for bare minimum",
        category: "yellow",
        score: 2,
        severity: "Litt problematisk",
        severityLevel: 2,
        isBareMinimum: false,
        themes: ["bare minimum", "modenhet", "innsats"],
        description: "Personen forventer mye ros for helt grunnleggende ting, som å være ærlig eller behandle deg normalt pent.",
        advice: "Det er fint å sette pris på hverandre, men minimumsrespekt bør ikke fremstilles som noe ekstraordinært."
    },
    {
        id: 30,
        title: "Tar ansvar etter konflikt",
        category: "green",
        score: -2,
        severity: "Positivt",
        severityLevel: 1,
        isBareMinimum: false,
        themes: ["konflikt", "ansvar", "modenhet"],
        description: "Personen kan snakke rolig etter en konflikt og prøve å forstå hva som skjedde.",
        advice: "Dette er et sterkt green flag fordi alle relasjoner kan ha misforståelser, men måten man reparerer på betyr mye."
    }
];